name: Java CI with Maven - Test and package

on:
  pull_request:
    branches:
      - main # Ce workflow se déclenche lors d'une pull request vers le main

jobs:
  build:
    name: Build and Test Java Application
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Utiliser l'action checkout pour se placer dans le dépôt courant
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configurer l'environnement Java (version 21, distribution corretto)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      # Étape 3 : Analyse de la qualité avec Maven
      - name: Analyse du qualiter
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')

